### PR TITLE
Add get_organs and glb files

### PR DESCRIPTION
**Pull request by hunterxtang**

### CODE REVIEW

**Comment by bherr2** [comment]
Please don't do this

**Comment by bherr2** [comment]
@andreasbueckle he should not be saving these GLB files to a repo like this. It goes against what we talked about. These assets can be part of a build artifact, but NOT committed.

**Comment by andreasbueckle** [comment]
Thanks @bherr2 

@hunterxtang 
Let's add the folder for downloaded GLB files plus all GLB files to ```gitignore```.

**Comment by bherr2** [comment]
Also add .DS_Store to .gitignore and remove

**Pull request closed without merging**
